$ python3 ransomware_detection.py
/home/rex/.local/lib/python3.10/site-packages/sklearn/utils/_array_api.py:185: RuntimeWarning: overflow encountered in cast
  array = numpy.asarray(array, order=order, dtype=dtype)
Traceback (most recent call last):
  File "/home/rex/ransomware_simulation/ransomware_detection.py", line 143, in <module>
    main()
  File "/home/rex/ransomware_simulation/ransomware_detection.py", line 139, in main
    notifier.loop()
  File "/home/rex/.local/lib/python3.10/site-packages/pyinotify.py", line 1376, in loop
    self.process_events()
  File "/home/rex/.local/lib/python3.10/site-packages/pyinotify.py", line 1275, in process_events
    self._default_proc_fun(revent)
  File "/home/rex/.local/lib/python3.10/site-packages/pyinotify.py", line 910, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/home/rex/.local/lib/python3.10/site-packages/pyinotify.py", line 630, in __call__
    return meth(event)
  File "/home/rex/ransomware_simulation/ransomware_detection.py", line 62, in process_IN_MODIFY
    self.iforest.fit(self.file_features)
  File "/home/rex/.local/lib/python3.10/site-packages/sklearn/ensemble/_iforest.py", line 290, in fit
    X = self._validate_data(X, accept_sparse=["csc"], dtype=tree_dtype)
  File "/home/rex/.local/lib/python3.10/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/home/rex/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 921, in check_array
    _assert_all_finite(
  File "/home/rex/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains infinity or a value too large for dtype('float32').
